[package]
name = "rusty_bash"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19"
termion = "1.5.6"
glob = "0.3.0"
unicode-width = "0.1.9"
rev_lines = "0.2.1"
ctrlc = "3.2.2"
