name: linux

on:
  push:
    branches: [ main, sd/* ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bash tests
      run: bash -xv ./test/test.bash
    - name: Old tests
      run: bash -xve ./test/old_test.bash
      #- name: Internal tests
      #run: cargo test --verbose
