name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bash tests
      run: bash -xv ./test/test.bash
      run: bash -xve ./test/old_test.bash
      #- name: Internal tests
      #run: cargo test --verbose
